[leveldb]
    mode    = "local"                          # LEVELDB_MODE
    path    = "/app/geth-rw/chaindata"         # LEVELDB_PATH
    ancient = "/app/geth-rw/chaindata/ancient" # LEVELDB_ANCIENT
    url     = "http://127.0.0.1:8082/"         # LEVELDB_URL

[server]
    ipcPath  = ".ipc"           # SERVICE_IPC_PATH
    httpPath = "0.0.0.0:8545" # SERVICE_HTTP_PATH

[statediff]
    prerun          = true  # STATEDIFF_PRERUN
    serviceWorkers  = 1     # STATEDIFF_SERVICE_WORKERS
    workerQueueSize = 1024  # STATEDIFF_WORKER_QUEUE_SIZE
    trieWorkers     = 16     # STATEDIFF_TRIE_WORKERS

[prerun]
    only = true     # PRERUN_ONLY
    parallel = true  # PRERUN_PARALLEL
    ranges = []

    # statediffing params for prerun
    [prerun.params]
        includeBlock             = true # PRERUN_INCLUDE_BLOCK
        includeReceipts          = true # PRERUN_INCLUDE_RECEIPTS
        includeTD                = true # PRERUN_INCLUDE_TD
        includeCode              = true # PRERUN_INCLUDE_CODE
        watchedAddresses         = []

[log]
    # Leave empty to output to stdout
    file  = ""      # LOG_FILE
    level = "debug" # LOG_LEVEL

[database]
    # output type <postgres | file | dump>
    type = "postgres"
    name     = ""      # DATABASE_NAME
    hostname = ""      # DATABASE_HOSTNAME
    port     = 5432    # DATABASE_PORT
    user     = ""      # DATABASE_USER
    password = ""      # DATABASE_PASSWORD
    driver   = ""      # DATABASE_DRIVER_TYPE

    # with file type
    # file mode <sql | csv>
    fileMode = "csv"   # DATABASE_FILE_MODE

    # with SQL file mode
    filePath = ""   # DATABASE_FILE_PATH

    # with CSV file mode
    fileCsvDir = "" # DATABASE_FILE_CSV_DIR

    # with dump type
    # <stdout | stderr | discard>
    dumpDestination = ""    # DATABASE_DUMP_DST

[cache]
    # settings for geth internal caches
    database = 1024 # DB_CACHE_SIZE_MB
    trie     = 4096 # TRIE_CACHE_SIZE_MB

[prom]
    # prometheus metrics
    metrics  = true         # PROM_METRICS
    http     = true         # PROM_HTTP
    httpAddr = "localhost"  # PROM_HTTP_ADDR
    httpPort = "8889"       # PROM_HTTP_PORT
    dbStats = true          # PROM_DB_STATS

[ethereum]
    # Identifiers for ethereum node
    nodeID       = ""                       # ETH_NODE_ID
    clientName   = "eth-statediff-service"  # ETH_CLIENT_NAME
    networkID    = 1                        # ETH_NETWORK_ID
    chainID      = 1                        # ETH_CHAIN_ID
    genesisBlock = ""                       # ETH_GENESIS_BLOCK
    chainConfig  = ""                       # ETH_CHAIN_CONFIG

[debug]
    pprof = false                           # DEBUG_PPROF
